## Config file
lr:              5e-5 # Initial learning rate
weight_decay:    5e-5
power:           0.9
epochs:          1000 # Number of epochs to train the model   
number_classes:  4 # Number of classes in the target dataset
batch_size_tr:   1 # Batch size for train
batch_size_va:   1 # Batch size for validationn 
modalities:      ['t2f', 't1n', 't1c', 't2w'] # fets: ['flair', 't1', 't1ce', 't2'] brats: ['t2f', 't1n', 't1c', 't2w']
path_to_data:    '/data/birth/cyf/shared_data/Pretreat-MetsToBrain-Masks' # path to datasets
path_to_log:     './log' # path to save results
path_to_train:   'jsons_retreat_0.1/Retreat_train_seed3407.json' # path to dataset
path_to_test:    'jsons_retreat_0.1/Retreat_test_seed3407.json'
progress_p:      0.1 # value between 0-1 shows the number of time we need to report training progress in each epoch
validation_p:    0.1 # validation percentage
test_p:          0.2 # Test percentage (20%)
inputshape:      [160, 192, 128]
weight_mispath:  0.6
weight_content:  0.2
dataset:         'retreat'
